version: '3'
# https://github.com/nacos-group/nacos-docker.git
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-mysql
    env_file:
      - env/nacos-standlone-mysql.env
    volumes:
      - /Users/yule/Documents/nacos_data/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
  mysql:
    container_name: Mysql
    build:
      context: .
      dockerfile: Env/Dockerfile
    image: Env/mysql:8.0.30
    env_file:
      - Env/mysql.env 
    volumes:
      - /Users/yule/Documents/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  consul1:
    image: consul:1.15.4
    container_name: consul1
    restart: always
    command: agent -server -bootstrap-expect=3 -node=consul1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/consul_data/consul1/data:/consul/data
      - /Users/yule/Documents/consul_data/consul1/config:/consul/config
  consul2:
    image: consul:1.15.4
    container_name: consul2
    restart: always
    command: agent -server -node=consul2 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1  -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/consul_data/consul2/data:/consul/data
      - /Users/yule/Documents/consul_data/consul2/config:/consul/config
    depends_on:
      - consul1
  consul3:
    image: consul:1.15.4
    container_name: consul3
    restart: always
    command: agent -server -node=consul3 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1 -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/consul_data/consul3/data:/consul/data
      - /Users/yule/Documents/consul_data/consul3/config:/consul/config
    depends_on:
      - consul1
  consul4:
    image: consul:1.15.4
    container_name: consul4
    restart: always
    ports:
      - "8500:8500"
    command: agent -server -node=client1 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1 -datacenter=dc1 -config-dir=/consul/config -ui
    volumes:
      - /Users/yule/Documents/consul_data/consul4/data:/consul/data
      - /Users/yule/Documents/consul_data/consul4/config:/consul/config
    depends_on:
      - consul2
      - consul3