version : '3.1'

services:
  db:
    image: mysql/mysql-server 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /Users/yule/Documents/mysql_data:/var/lib/mysql