version: '3'
# https://github.com/nacos-group/nacos-docker.git
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    volumes:
      - /Users/yule/Documents/GoMicDockerData/nacos1:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9868:9848"
      - "9850:9849"
    env_file:
      - ../nacos-hostname.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  nacos2:
    hostname: nacos2
    container_name: nacos2
    image: nacos/nacos-server:latest
    volumes:
      - /Users/yule/Documents/GoMicDockerData/nacos2:/home/nacos/logs
    ports:
      - "7849:7848"
      - "8849:8848"
      - "9869:9848"
      - "9851:9849"
    env_file:
      - ../nacos-hostname.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  nacos3:
    hostname: nacos3
    container_name: nacos3
    image: nacos/nacos-server:latest
    volumes:
      - /Users/yule/Documents/GoMicDockerData/nacos3:/home/nacos/logs
    ports:
      - "7850:7848"
      - "8850:8848"
      - "9870:9848"
      - "9852:9849"
    env_file:
      - ../nacos-hostname.env
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ../Dockerfile
    image: nacos/mysql:8
    env_file:
      - ../mysql.env
    volumes:
      - /Users/yule/Documents/GoMicDockerData/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  consul1:
    image: consul:1.15.4
    container_name: consul1
    restart: always
    command: agent -server -bootstrap-expect=3 -node=consul1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul1/data:/consul/data
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul1/config:/consul/config
  consul2:
    image: consul:1.15.4
    container_name: consul2
    restart: always
    command: agent -server -node=consul2 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1  -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul2/data:/consul/data
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul2/config:/consul/config
    depends_on:
      - consul1
  consul3:
    image: consul:1.15.4
    container_name: consul3
    restart: always
    command: agent -server -node=consul3 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1 -datacenter=dc1 -config-dir=/consul/config
    volumes:
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul3/data:/consul/data
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul3/config:/consul/config
    depends_on:
      - consul1
  consul4:
    image: consul:1.15.4
    container_name: consul4
    restart: always
    ports:
      - "8500:8500"
    command: agent -server -node=client1 -bind=0.0.0.0 -client=0.0.0.0 -retry-join=consul1 -datacenter=dc1 -config-dir=/consul/config -ui
    volumes:
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul4/data:/consul/data
      - /Users/yule/Documents/GoMicDockerData/consul_data/consul4/config:/consul/config
    depends_on:
      - consul2
      - consul3